### ISSUE TITLE
"Malicious dependency detected" - Still succeeds

### ISSUE THREAD

**Issue by crxgames** [acordiner92/npm-audit-pipeline#160]
It seems that the package does not catch the "malicious dependency detected" coming from within npm. 

`> pxxx-backend-services@2.0.0 package-audit /opt/atlassian/pipelines/agent/build
> npm-audit --low=4 --moderate=3 --high=0 --critical=0 --retry=3
 
Malicious dependency detected
 Package: mariadb
 File: /opt/atlassian/pipelines/agent/build/node_modules/sequelize/package.json
 For more information, visit https://github.com/jshanson7/npm-audit
audited 1061 packages`

Command succeeds and build continues on.

**Comment by acordiner92** [comment]
Hey, thanks for raising this issue, and sorry for the late reply! Sounds like a valid case that was missed. I'll be adding a fix for the scenario soon as I got a bit of time to work on it again.

**Comment by acordiner92** [comment]
Hey, thanks for raising this issue, and sorry for the late reply! Sounds like a valid case that was missed. I'll be adding a fix for the scenario soon as I got a bit of time to work on it again

**Comment by acordiner92** [comment]
Upon further investigation, there are only 5 error types provided by NPM which include info, low, medium, high, critical. From analyzing your error message it refers to the library npm-audit which is an entirely different library to npm-audit-pipeline and therefore I believe that is where your problem lies. To get it working you need to install the library as follows:
 `npm i npm-audit-pipeline -D` and then in your package json add 
```
"scripts": {
  "package-audit": "npm-audit"
}
```
From here you can run the command `npm run npm-audit`. Hope that helps! I'll be closing this out since it's no longer considered a bug.
