### ISSUE TITLE
Different result between "npm audit" and npm-audit-pipeline

### ISSUE THREAD

**Issue by hgenr** [acordiner92/npm-audit-pipeline#211]
Hi, 

thanks for the great work! I'm wondering about a difference between running "npm audit" and running this code. In a test project (see package.json below) "npm audit" finds 16 moderate vulnerabilities but npm-audit-pipeline tells me "For level: moderate, the expected vulnerabilities should be 0 but got 5".

Here the package.json:

`{
  "name": "audit-pipeline-test",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "package-audit": "npm-audit"
  },
  "dependencies": {
    "semantic-release": "^18.0.1"
  },
  "devDependencies": {
    "npm-audit-pipeline": "^0.6.0"
  }
}` 

Here the output (only the metadata part) of npm audit --json:

`  "metadata": {
    "vulnerabilities": {
      "info": 0,
      "low": 0,
      "moderate": 16,
      "high": 0,
      "critical": 0
    },
    "dependencies": 570,
    "devDependencies": 6,
    "optionalDependencies": 5,
    "totalDependencies": 581
  },`

Environment:
Ubuntu 20.04
npm 6.14.15
node 14.18.2

**Comment by acordiner92** [comment]
Hey hgenr,
Thanks for reporting this issue and providing a replicable example to go with it. I will take a look at this over the coming days to see what is going on

**Comment by acordiner92** [comment]
Okay, I found the problem. It is cos when the child node is spawned it uses the npm version from your npm lib inside node_modules which would most likely be 7+ version rather than npm 6.14.15 which is currently being used in your terminal.
Npm must have changed some logic around vulernabilties in audit because when you run audit on v6 and v7+ it show the following:

`v6.14.15: npm audit --json  ===> "metadata": { "vulnerabilities": { "info": 0, "low": 0, "moderate": 16, "high": 0, "critical": 0 },`

`v7.24.2: npm audit --json  ===> "metadata": { "vulnerabilities": { "info": 0, "low": 0, "moderate": 5, "high": 0, "critical": 0 },`

There are 2 work around solutions I can think of from the top of my head for now.
1. Upgrading your local version to npm 7+ so it aligns with what has been run in npm-audit
2. Setting the npm version in your package.json to constrain it to your local version with
    `npm i npm@6.14.15 -D` 

I'll be looking into getting a proper solution soon

**Comment by hgenr** [comment]
Hi acordiner92,

thank you for digging into the issue! I didn't notice that semantic-release comes with its own npm. I can reproduce the behavior. Looks like npm 8.x (I'm thinking about upgrading to node 16.x and npm 8.x) and 7.x behaves the same when scanning for vulnerabilities.

Happy new year (in advance) and thanks for providing the solution options!

**Comment by acordiner92** [comment]
Okay, that is good you can do an npm upgrade in your case. I also managed to get a fix to make it work correctly now with your situation. So now it should always use your local terminal version. Example:
```
❯ nvm use 17.1.0
Now using node v17.1.0 (npm v8.1.4)
❯ npm run package-audit

> package-audit
> npm-audit

  NPM AUDIT FAILED
  For level: moderate, the expected vulnerabilities should be 0 but got 5

...

❯ nvm use 14.18.2
Now using node v14.18.2 (npm v6.14.15)
❯ npm run package-audit

> @ package-audit /Users/andrewcordiner/Documents/personal-projects/npm-audit-pipeline/demo/npm
> npm-audit

  NPM AUDIT FAILED
  For level: moderate, the expected vulnerabilities should be 0 but got 16
```

You can try it out on version [0.6.1](https://www.npmjs.com/package/npm-audit-pipeline/v/0.6.1)

If you have any other problems, feel free to create new issues, and happy new year to you too :)

**Comment by hgenr** [comment]
Great, I can confirm that it now produces the same result for npm 6.x on my machine!
